from typing import Union as _Union

RichText = _Union[
    "RichTextBold",
    "RichTextItalic",
    "RichTextUnderline",
    "RichTextStrikethrough",
    "RichTextSpoiler",
    "RichTextDateTime",
    "RichTextTextMention",
    "RichTextSubscript",
    "RichTextSuperscript",
    "RichTextMarked",
    "RichTextCode",
    "RichTextCustomEmoji",
    "RichTextMathematicalExpression",
    "RichTextUrl",
    "RichTextEmailAddress",
    "RichTextPhoneNumber",
    "RichTextBankCardNumber",
    "RichTextMention",
    "RichTextHashtag",
    "RichTextCashtag",
    "RichTextBotCommand",
    "RichTextAnchor",
    "RichTextAnchorLink",
    "RichTextReference",
    "RichTextReferenceLink",
]
